# Generated by Django 4.2.7 on 2023-12-14 06:24

import balance.custom_validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(validators=[balance.custom_validators.validate_year])),
                ('month', models.IntegerField(validators=[balance.custom_validators.validate_month])),
                ('first_day_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_day_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.sources', verbose_name='source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'year', 'month', 'source')},
            },
        ),
    ]
