# Generated by Django 4.2.7 on 2024-12-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='send_monthly_report',
            field=models.BooleanField(default=False),
        ),
    ]
