# Generated by Django 4.2.7 on 2023-12-14 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'credit'), ('debit', 'debit'), ('transfer', 'transfer')], max_length=10, verbose_name='transaction_type'),
        ),
        migrations.CreateModel(
            name='InternalTransactions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comments', models.TextField(verbose_name='comments')),
                ('destination', models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination', to='transactions.sources', verbose_name='destination')),
                ('source', models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source', to='transactions.sources', verbose_name='source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
