# Generated by Django 4.2.7 on 2024-04-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transactions_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sources',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
