# Generated by Django 4.2.7 on 2024-06-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_commodity_is_deleted_sources_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
